# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.2.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test
      - run: yarn build

    deploy:
      machine:
        enabled: true
      steps:
        - add_ssh_keys:
            fingerprints:
              - $TARGET_SERVER_SSH_FINGERPRINT
            
        - run:
            name: Deploy build result to server
            command: |
              scp -o StrictHostKeyChecking=no \ 
                ./public $TARGET_SERVER_USER_NAME@$TARGET_SERVER_ADDRESS:$TARGET_DEPLOYMENT_PATH
            # command: |
            #   ssh -o StrictHostKeyChecking=no \
            #     $TARGET_SERVER_USER_NAME@$TARGET_SERVER_ADDRESS \
            #     "/bin/bash $DEPLOYMENT_SCRIPT_FILE_PATH"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master